export const workoutTemplates = [
  {
    id: "sheet-120-kettlebell-full-body",
    name: "Kettlebell Full Body",
    source: "2026 Home Workout Sheet - tab 120",
    description: "A balanced hinge, squat, pull, shoulder, and core workout adapted from your home workout log.",
    tags: ["kettlebell", "full-body", "home"],
    cycles: 3,
    movements: [
      { move: "Single-Leg Deadlift (L)", target: "30 sec", pattern: "Hinge", cue: "Reach hips back and keep the bell close." },
      { move: "Single-Leg Deadlift (R)", target: "30 sec", pattern: "Hinge", cue: "Match the left side with a quiet torso." },
      { move: "Goblet Squat", target: "30 sec", pattern: "Squat", cue: "Stay tall and drive through mid-foot." },
      { move: "Bent Row (Alt)", target: "30 sec", pattern: "Pull", cue: "Hinge, brace, and pull elbow toward ribs." },
      { move: "Dead High Pull (Alt)", target: "30 sec", pattern: "Pull", cue: "Snap from hips before the elbow rises." },
      { move: "Kettlebell Halos (Alt)", target: "30 sec", pattern: "Mobility", cue: "Ribs down while the bell circles the head." },
      { move: "Goblet Front Side Raise (Alt)", target: "30 sec", pattern: "Shoulders", cue: "Use control, not momentum." },
      { move: "Goblet Overhead March", target: "30 sec", pattern: "Carry", cue: "Lock ribs down and march slowly." },
      { move: "Scissor Leg Raise (Alt)", target: "30 sec", pattern: "Core", cue: "Keep low back heavy on the floor." },
      { move: "Reverse Plank", target: "30 sec", pattern: "Core", cue: "Squeeze glutes and open the chest." },
    ],
  },
  {
    id: "sheet-115-push-pull-burner",
    name: "Push + Pull Burner",
    source: "2026 Home Workout Sheet - tab 115",
    description: "A simple conditioning circuit built around pushups, rows, swings, and burpees.",
    tags: ["strength", "push", "pull"],
    cycles: 5,
    movements: [
      { move: "Burpees", target: "5 reps", pattern: "Conditioning", cue: "Move smoothly and keep reps clean." },
      { move: "Pushups", target: "10 reps", pattern: "Push", cue: "Brace like a plank." },
      { move: "Bent Row (L)", target: "15 reps", pattern: "Pull", cue: "Pull shoulder blade back, then elbow." },
      { move: "Bent Row (R)", target: "15 reps", pattern: "Pull", cue: "Keep hips square." },
      { move: "Russian Swings", target: "20 reps", pattern: "Hinge", cue: "Hips drive the bell, arms guide it." },
    ],
  },
  {
    id: "sheet-112-single-leg-strength",
    name: "Single-Leg Strength",
    source: "2026 Home Workout Sheet - tab 112",
    description: "A unilateral strength session from your log with deadrows, squats, pulls, halos, and overhead marching.",
    tags: ["kettlebell", "legs", "strength"],
    cycles: 4,
    movements: [
      { move: "Single Leg Deadrow (L)", target: "30 sec", pattern: "Hinge", cue: "Balance first, row second." },
      { move: "Single Leg Deadrow (R)", target: "30 sec", pattern: "Hinge", cue: "Keep the standing foot rooted." },
      { move: "Goblet Squat", target: "30 sec", pattern: "Squat", cue: "Elbows track inside knees." },
      { move: "Bent Row (Alt)", target: "30 sec", pattern: "Pull", cue: "Pause briefly at the top." },
      { move: "Dead High Pull (Alt)", target: "30 sec", pattern: "Pull", cue: "Use hips before arms." },
      { move: "Kettlebell Halos (Alt)", target: "30 sec", pattern: "Mobility", cue: "Keep neck long and still." },
      { move: "Side to Front Raise (Alt)", target: "30 sec", pattern: "Shoulders", cue: "Move through a pain-free range." },
      { move: "Overhead March", target: "30 sec", pattern: "Carry", cue: "Slow steps, tall posture." },
    ],
  },
  {
    id: "sheet-119-kb-core-mix",
    name: "KB + Core Mix",
    source: "2026 Home Workout Sheet - tab 119",
    description: "A compact kettlebell and floor-core blend for conditioning, trunk work, and shoulders.",
    tags: ["kettlebell", "core", "conditioning"],
    cycles: 2,
    movements: [
      { move: "KB Cross Lunge", target: "30 sec", pattern: "Lunge", cue: "Step with control and keep chest tall." },
      { move: "Shoulder Toss", target: "30 sec", pattern: "Power", cue: "Use a light bell and crisp hand exchange." },
      { move: "KB Curl", target: "30 sec", pattern: "Arms", cue: "Keep elbows tucked." },
      { move: "KB Pullover", target: "30 sec", pattern: "Core", cue: "Ribs down as the bell moves overhead." },
      { move: "Upright Row Shoulder Press", target: "30 sec", pattern: "Push", cue: "Pull close, then press under control." },
      { move: "Pushups", target: "30 reps", pattern: "Push", cue: "Break into small sets if needed." },
      { move: "Russian Twists with KB", target: "30 reps", pattern: "Core", cue: "Rotate ribs, not just arms." },
      { move: "Sit Ups", target: "30 reps", pattern: "Core", cue: "Use control on the way down." },
    ],
  },
  {
    id: "research-beginner-full-body",
    name: "Beginner Full-Body Base",
    source: "Research: Woman & Home beginner kettlebell workout",
    description: "A beginner-friendly full-body EMOM using the classic swing, squat, row, press, and lunge pattern.",
    tags: ["beginner", "full-body", "strength"],
    cycles: 4,
    movements: [
      { move: "Kettlebell Swing", target: "30 sec", pattern: "Hinge", cue: "Hinge first; let the hips power the bell." },
      { move: "Goblet Squat", target: "30 sec", pattern: "Squat", cue: "Keep weight in heels and mid-foot." },
      { move: "One-Arm Row (L)", target: "30 sec", pattern: "Pull", cue: "Hinge and pull elbow toward ribs." },
      { move: "One-Arm Row (R)", target: "30 sec", pattern: "Pull", cue: "Keep shoulders square." },
      { move: "Overhead Press (L)", target: "30 sec", pattern: "Push", cue: "Brace before pressing overhead." },
      { move: "Overhead Press (R)", target: "30 sec", pattern: "Push", cue: "Lower with control." },
      { move: "Goblet Reverse Lunge (Alt)", target: "30 sec", pattern: "Lunge", cue: "Step back slowly and stand tall." },
    ],
  },
  {
    id: "research-total-body-strength",
    name: "Total-Body Strength Circuit",
    source: "Research: Health full-body kettlebell workout",
    description: "A strength-focused circuit built from squat-to-press, rows, swings, floor press, cleans, and deadlifts.",
    tags: ["strength", "full-body", "conditioning"],
    cycles: 3,
    movements: [
      { move: "Goblet Squat to Press", target: "30 sec", pattern: "Squat", cue: "Stand from the squat into a strong press." },
      { move: "Bent-Over Row (L)", target: "30 sec", pattern: "Pull", cue: "Squeeze shoulder blade before lowering." },
      { move: "Bent-Over Row (R)", target: "30 sec", pattern: "Pull", cue: "Brace and keep hips level." },
      { move: "Kettlebell Swing", target: "30 sec", pattern: "Hinge", cue: "Explosive hips, relaxed arms." },
      { move: "Bridge Chest Press (L)", target: "30 sec", pattern: "Push", cue: "Glutes up while the press stays smooth." },
      { move: "Bridge Chest Press (R)", target: "30 sec", pattern: "Push", cue: "Keep hips square." },
      { move: "Single-Arm Clean (L)", target: "30 sec", pattern: "Power", cue: "Zip the bell close to the body." },
      { move: "Single-Arm Clean (R)", target: "30 sec", pattern: "Power", cue: "Catch softly in the rack." },
      { move: "Kettlebell Deadlift", target: "30 sec", pattern: "Hinge", cue: "Push floor away and stand tall." },
    ],
  },
  {
    id: "research-mobility-core-engine",
    name: "Mobility + Core Engine",
    source: "Research: Fit&Well 10-minute full-body circuit",
    description: "A mobility-heavy full-body workout emphasizing hips, core, shoulders, and the posterior chain.",
    tags: ["mobility", "core", "full-body"],
    cycles: 2,
    movements: [
      { move: "Kettlebell Swing", target: "30 sec", pattern: "Hinge", cue: "Stay snappy but smooth." },
      { move: "Kettlebell Halo", target: "30 sec", pattern: "Mobility", cue: "Circle the bell without flaring ribs." },
      { move: "Figure-Eight to Hold", target: "30 sec", pattern: "Core", cue: "Pass around legs and pause tall." },
      { move: "Deadlift to Upright Row", target: "30 sec", pattern: "Pull", cue: "Hinge, stand, then row close." },
      { move: "Offset Squat (L)", target: "30 sec", pattern: "Squat", cue: "Rack bell left; resist leaning." },
      { move: "Offset Squat (R)", target: "30 sec", pattern: "Squat", cue: "Rack bell right; keep knees tracking." },
      { move: "Offset Pushup", target: "30 sec", pattern: "Push", cue: "One hand elevated if comfortable." },
      { move: "Around-the-World Lunge", target: "30 sec", pattern: "Lunge", cue: "Step through lunge angles under control." },
    ],
  },
  {
    id: "research-stability-power",
    name: "Stability + Power",
    source: "Research: Fit&Well strength, stability, and power moves",
    description: "A more athletic full-body session with cleans, lunges, presses, and single-arm swings.",
    tags: ["power", "stability", "athletic"],
    cycles: 3,
    movements: [
      { move: "Goblet Clean to Halo", target: "30 sec", pattern: "Mobility", cue: "Clean close, then halo slowly." },
      { move: "Lateral Lunge Clean (L)", target: "30 sec", pattern: "Lunge", cue: "Push out of the side hip to clean." },
      { move: "Lateral Lunge Clean (R)", target: "30 sec", pattern: "Lunge", cue: "Drive back to center with control." },
      { move: "Half-Kneeling Clean + Press (L)", target: "30 sec", pattern: "Push", cue: "Press knee into floor and brace." },
      { move: "Half-Kneeling Clean + Press (R)", target: "30 sec", pattern: "Push", cue: "No leg momentum; own the press." },
      { move: "Single-Arm Swing (L)", target: "30 sec", pattern: "Hinge", cue: "Fight rotation through the trunk." },
      { move: "Single-Arm Swing (R)", target: "30 sec", pattern: "Hinge", cue: "Hips snap, shoulder packed." },
    ],
  },
  {
    id: "research-get-up-practice",
    name: "Get-Up Practice",
    source: "Research: SELF Turkish get-up guide",
    description: "A slower control-focused workout for shoulder stability, core control, lunging, and getting up from the floor.",
    tags: ["mobility", "stability", "core"],
    cycles: 3,
    movements: [
      { move: "Half Turkish Get-Up (L)", target: "30 sec", pattern: "Core", cue: "Roll to elbow, then hand; eyes on bell." },
      { move: "Half Turkish Get-Up (R)", target: "30 sec", pattern: "Core", cue: "Move slowly through each checkpoint." },
      { move: "Tall Kneeling Halo", target: "30 sec", pattern: "Mobility", cue: "Glutes tight and ribs stacked." },
      { move: "Rack Reverse Lunge (L)", target: "30 sec", pattern: "Lunge", cue: "Front foot grounded and torso tall." },
      { move: "Rack Reverse Lunge (R)", target: "30 sec", pattern: "Lunge", cue: "Control the descent." },
      { move: "Suitcase March (L)", target: "30 sec", pattern: "Carry", cue: "Do not lean away from the bell." },
      { move: "Suitcase March (R)", target: "30 sec", pattern: "Carry", cue: "Slow knees and quiet ribs." },
    ],
  },
  {
    id: "science-muscle-full-body",
    name: "Muscle Gain: Full Body",
    source: "Research: 2026 kettlebell hypertrophy review",
    description: "A hypertrophy-biased kettlebell session covering squat, hinge, push, pull, press, and carry patterns.",
    tags: ["hypertrophy", "full-body", "kettlebell", "men"],
    cycles: 4,
    movements: [
      {
        move: "Goblet Squat",
        target: "8-12 reps",
        pattern: "Squat",
        cue: "Use a heavy bell, slow the descent, and stop 1-3 reps before form breaks.",
        primaryMuscles: ["Quadriceps", "Gluteus maximus"],
        secondaryMuscles: ["Adductors", "Hamstrings", "Erector spinae", "Rectus abdominis", "Obliques"],
      },
      {
        move: "Kettlebell Floor Press (L)",
        target: "8-12 reps",
        pattern: "Push",
        cue: "Elbow about 45 degrees from ribs; pause lightly on the floor.",
        primaryMuscles: ["Pectoralis major", "Triceps brachii", "Anterior deltoid"],
        secondaryMuscles: ["Serratus anterior", "Rotator cuff", "Forearms"],
      },
      {
        move: "Kettlebell Floor Press (R)",
        target: "8-12 reps",
        pattern: "Push",
        cue: "Match reps and control from the left side.",
        primaryMuscles: ["Pectoralis major", "Triceps brachii", "Anterior deltoid"],
        secondaryMuscles: ["Serratus anterior", "Rotator cuff", "Forearms"],
      },
      {
        move: "Bent-Over Row (L)",
        target: "8-12 reps",
        pattern: "Pull",
        cue: "Brace the hinge and pull elbow toward back pocket.",
        primaryMuscles: ["Latissimus dorsi", "Rhomboids", "Middle trapezius", "Posterior deltoid"],
        secondaryMuscles: ["Biceps brachii", "Brachialis", "Forearms", "Erector spinae"],
      },
      {
        move: "Bent-Over Row (R)",
        target: "8-12 reps",
        pattern: "Pull",
        cue: "Keep shoulders square and pause at the top.",
        primaryMuscles: ["Latissimus dorsi", "Rhomboids", "Middle trapezius", "Posterior deltoid"],
        secondaryMuscles: ["Biceps brachii", "Brachialis", "Forearms", "Erector spinae"],
      },
      {
        move: "Single-Arm Clean + Press (L)",
        target: "5-8 reps",
        pattern: "Push",
        cue: "Clean close, press without leaning back, and own the lockout.",
        primaryMuscles: ["Deltoids", "Triceps brachii", "Gluteus maximus", "Hamstrings"],
        secondaryMuscles: ["Trapezius", "Latissimus dorsi", "Rectus abdominis", "Obliques", "Forearms"],
      },
      {
        move: "Single-Arm Clean + Press (R)",
        target: "5-8 reps",
        pattern: "Push",
        cue: "Zip the bell close and finish stacked wrist-over-elbow-over-shoulder.",
        primaryMuscles: ["Deltoids", "Triceps brachii", "Gluteus maximus", "Hamstrings"],
        secondaryMuscles: ["Trapezius", "Latissimus dorsi", "Rectus abdominis", "Obliques", "Forearms"],
      },
      {
        move: "Kettlebell Swing",
        target: "12-18 reps",
        pattern: "Hinge",
        cue: "Explosive hips, neutral spine, and arms as hooks.",
        primaryMuscles: ["Gluteus maximus", "Hamstrings"],
        secondaryMuscles: ["Erector spinae", "Adductor magnus", "Latissimus dorsi", "Rectus abdominis", "Forearms"],
      },
    ],
  },
  {
    id: "science-muscle-core",
    name: "Muscle Gain: Core",
    source: "Research: 2026 kettlebell hypertrophy review",
    description: "Core work biased toward anti-rotation, anti-lateral flexion, bracing, trunk control, and shoulder stability.",
    tags: ["hypertrophy", "core", "kettlebell", "stability"],
    cycles: 4,
    movements: [
      {
        move: "Suitcase March (L)",
        target: "30 sec",
        pattern: "Carry",
        cue: "Stay tall and do not lean away from the bell.",
        primaryMuscles: ["Obliques", "Quadratus lumborum", "Transverse abdominis"],
        secondaryMuscles: ["Gluteus medius", "Forearms", "Trapezius"],
      },
      {
        move: "Suitcase March (R)",
        target: "30 sec",
        pattern: "Carry",
        cue: "Slow knees, level shoulders, quiet ribs.",
        primaryMuscles: ["Obliques", "Quadratus lumborum", "Transverse abdominis"],
        secondaryMuscles: ["Gluteus medius", "Forearms", "Trapezius"],
      },
      {
        move: "Half Turkish Get-Up (L)",
        target: "2-4 reps",
        pattern: "Core",
        cue: "Roll to elbow, press to hand, and keep eyes on the bell.",
        primaryMuscles: ["Rectus abdominis", "Obliques", "Deltoids", "Rotator cuff"],
        secondaryMuscles: ["Serratus anterior", "Gluteus maximus", "Hip flexors", "Triceps brachii"],
      },
      {
        move: "Half Turkish Get-Up (R)",
        target: "2-4 reps",
        pattern: "Core",
        cue: "Move through each checkpoint slowly.",
        primaryMuscles: ["Rectus abdominis", "Obliques", "Deltoids", "Rotator cuff"],
        secondaryMuscles: ["Serratus anterior", "Gluteus maximus", "Hip flexors", "Triceps brachii"],
      },
      {
        move: "Kettlebell Pull-Through Plank",
        target: "8-12 drags",
        pattern: "Core",
        cue: "Drag the bell without letting hips rotate.",
        primaryMuscles: ["Transverse abdominis", "Obliques", "Rectus abdominis"],
        secondaryMuscles: ["Latissimus dorsi", "Deltoids", "Serratus anterior", "Gluteus maximus"],
      },
      {
        move: "Russian Twists with KB",
        target: "12-20 reps",
        pattern: "Core",
        cue: "Rotate ribs under control; avoid yanking with arms.",
        primaryMuscles: ["Obliques", "Rectus abdominis"],
        secondaryMuscles: ["Transverse abdominis", "Hip flexors", "Erector spinae", "Forearms"],
      },
      {
        move: "Tall Kneeling Halo",
        target: "8-10 each way",
        pattern: "Mobility",
        cue: "Squeeze glutes and keep ribs stacked while the bell circles.",
        primaryMuscles: ["Deltoids", "Rotator cuff", "Serratus anterior"],
        secondaryMuscles: ["Rectus abdominis", "Obliques", "Trapezius", "Forearms"],
      },
      {
        move: "Kettlebell Pullover Dead Bug",
        target: "8-12 reps",
        pattern: "Core",
        cue: "Low back stays heavy as the bell moves overhead.",
        primaryMuscles: ["Rectus abdominis", "Transverse abdominis", "Latissimus dorsi"],
        secondaryMuscles: ["Serratus anterior", "Triceps brachii", "Hip flexors"],
      },
    ],
  },
  {
    id: "science-muscle-legs",
    name: "Muscle Gain: Legs",
    source: "Research: 2026 kettlebell hypertrophy review",
    description: "Lower-body hypertrophy using squat, lunge, split-squat, hinge, bridge, and swing patterns.",
    tags: ["hypertrophy", "legs", "glutes", "kettlebell"],
    cycles: 4,
    movements: [
      {
        move: "Goblet Squat",
        target: "10-15 reps",
        pattern: "Squat",
        cue: "Use depth you can control and keep tension on quads.",
        primaryMuscles: ["Quadriceps", "Gluteus maximus"],
        secondaryMuscles: ["Adductors", "Hamstrings", "Erector spinae", "Rectus abdominis"],
      },
      {
        move: "Front-Rack Reverse Lunge (L)",
        target: "8-12 reps",
        pattern: "Lunge",
        cue: "Front foot stays rooted; stand through the front leg.",
        primaryMuscles: ["Quadriceps", "Gluteus maximus"],
        secondaryMuscles: ["Hamstrings", "Adductors", "Gluteus medius", "Obliques"],
      },
      {
        move: "Front-Rack Reverse Lunge (R)",
        target: "8-12 reps",
        pattern: "Lunge",
        cue: "Match stride length and knee control.",
        primaryMuscles: ["Quadriceps", "Gluteus maximus"],
        secondaryMuscles: ["Hamstrings", "Adductors", "Gluteus medius", "Obliques"],
      },
      {
        move: "Kettlebell Romanian Deadlift",
        target: "8-12 reps",
        pattern: "Hinge",
        cue: "Hips back, slight knee bend, feel hamstrings load.",
        primaryMuscles: ["Hamstrings", "Gluteus maximus", "Erector spinae"],
        secondaryMuscles: ["Adductor magnus", "Latissimus dorsi", "Forearms", "Trapezius"],
      },
      {
        move: "Goblet Split Squat (L)",
        target: "8-12 reps",
        pattern: "Lunge",
        cue: "Drop straight down and keep front knee tracking.",
        primaryMuscles: ["Quadriceps", "Gluteus maximus"],
        secondaryMuscles: ["Hamstrings", "Adductors", "Gluteus medius", "Calves"],
      },
      {
        move: "Goblet Split Squat (R)",
        target: "8-12 reps",
        pattern: "Lunge",
        cue: "Own the bottom position before driving up.",
        primaryMuscles: ["Quadriceps", "Gluteus maximus"],
        secondaryMuscles: ["Hamstrings", "Adductors", "Gluteus medius", "Calves"],
      },
      {
        move: "Kettlebell Glute Bridge",
        target: "10-15 reps",
        pattern: "Hinge",
        cue: "Pause hard at the top without arching low back.",
        primaryMuscles: ["Gluteus maximus", "Hamstrings"],
        secondaryMuscles: ["Adductor magnus", "Rectus abdominis", "Erector spinae"],
      },
      {
        move: "Kettlebell Swing",
        target: "12-20 reps",
        pattern: "Hinge",
        cue: "Finish with glutes, not low back.",
        primaryMuscles: ["Gluteus maximus", "Hamstrings"],
        secondaryMuscles: ["Erector spinae", "Adductor magnus", "Latissimus dorsi", "Forearms"],
      },
    ],
  },
  {
    id: "science-muscle-upper",
    name: "Muscle Gain: Upper Body",
    source: "Research: 2026 kettlebell hypertrophy review",
    description: "Upper-body hypertrophy for chest, back, shoulders, arms, grip, and shoulder-stability muscles.",
    tags: ["hypertrophy", "upper-body", "kettlebell", "shoulders"],
    cycles: 4,
    movements: [
      {
        move: "Kettlebell Floor Press (L)",
        target: "8-12 reps",
        pattern: "Push",
        cue: "Press hard and pause on the floor each rep.",
        primaryMuscles: ["Pectoralis major", "Triceps brachii", "Anterior deltoid"],
        secondaryMuscles: ["Serratus anterior", "Rotator cuff", "Forearms"],
      },
      {
        move: "Kettlebell Floor Press (R)",
        target: "8-12 reps",
        pattern: "Push",
        cue: "Keep shoulder packed and wrist stacked.",
        primaryMuscles: ["Pectoralis major", "Triceps brachii", "Anterior deltoid"],
        secondaryMuscles: ["Serratus anterior", "Rotator cuff", "Forearms"],
      },
      {
        move: "Bent-Over Row (L)",
        target: "8-12 reps",
        pattern: "Pull",
        cue: "Pull elbow low and back; pause at ribs.",
        primaryMuscles: ["Latissimus dorsi", "Rhomboids", "Middle trapezius", "Posterior deltoid"],
        secondaryMuscles: ["Biceps brachii", "Brachialis", "Forearms", "Erector spinae"],
      },
      {
        move: "Bent-Over Row (R)",
        target: "8-12 reps",
        pattern: "Pull",
        cue: "Brace the hinge and avoid twisting.",
        primaryMuscles: ["Latissimus dorsi", "Rhomboids", "Middle trapezius", "Posterior deltoid"],
        secondaryMuscles: ["Biceps brachii", "Brachialis", "Forearms", "Erector spinae"],
      },
      {
        move: "Overhead Press (L)",
        target: "6-10 reps",
        pattern: "Push",
        cue: "Brace glutes and ribs before pressing.",
        primaryMuscles: ["Deltoids", "Triceps brachii"],
        secondaryMuscles: ["Upper trapezius", "Serratus anterior", "Rotator cuff", "Obliques"],
      },
      {
        move: "Overhead Press (R)",
        target: "6-10 reps",
        pattern: "Push",
        cue: "Lock out with biceps near ear and no lean-back.",
        primaryMuscles: ["Deltoids", "Triceps brachii"],
        secondaryMuscles: ["Upper trapezius", "Serratus anterior", "Rotator cuff", "Obliques"],
      },
      {
        move: "Kettlebell Pullover",
        target: "8-12 reps",
        pattern: "Pull",
        cue: "Ribs down and elbows softly bent.",
        primaryMuscles: ["Latissimus dorsi", "Pectoralis major", "Serratus anterior"],
        secondaryMuscles: ["Triceps brachii", "Rectus abdominis", "Rotator cuff"],
      },
      {
        move: "Kettlebell Curl",
        target: "10-15 reps",
        pattern: "Pull",
        cue: "Keep elbows pinned and squeeze the handle hard.",
        primaryMuscles: ["Biceps brachii", "Brachialis", "Brachioradialis"],
        secondaryMuscles: ["Forearms", "Anterior deltoid", "Rectus abdominis"],
      },
    ],
  },
];

export function expandTemplate(template) {
  return Array.from({ length: template.cycles }).flatMap((_, cycleIndex) =>
    template.movements.map((movement, movementIndex) => ({
      ...movement,
      cycle: cycleIndex + 1,
      movementIndex: movementIndex + 1,
    })),
  );
}
